export const darkBlue = '#05386B'
export const darkGreen = '#379683'
export const green = '#5CDB95'
export const softGreen = '#8EE4AF'
export const softPurple = '#E3E7DC'
export const white = '#EDF5E1'
export const moreGreen = '#E5F7C8'
export const lessDarkGreen = '#5CA879'