export const darkBlue = '#05386B'
export const brightWhite = '#F3F5EF'
export const darkGreen = '#379683'
export const green = '#5CDB95'
export const softGreen = '#8EE4AF'
export const softPurple = '#E3E7DC'
export const softBlue = '#6395C7'
export const white = '#EDF5E1'
export const moreGreen = '#E5F7C8'
export const lessDarkGreen = '#5CA879'
export const grey = '#E6E6E6'
export const softGrey = '#79869D'

export const newBlue = '#607EAA'
export const moreGrey = '#EAE3D2'
export const lightCream = '#F9F5EB'